name: meichu

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8005:80
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: meichu-frontend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    image: meichu-backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true